# Let's manipulate some arrays! 
In this notebook we will see different wasy in which we can manipulate an array

## Exercise 1 Array accessing 
Given an ndarray x = [[3.0, 2.0, 5.0], [1.0, 4.0, 2.0], [6.0, 7.0, 8.0]]
Return two arrays:
1) Compute the mean of the elements along the second column 
2) Retrieve the elements with values higher than 2 along the second and third rows 

In [21]:
import numpy as np

x= np.array([[3.0, 2.0, 5.0], [1.0, 4.0, 2.0], [6.0, 7.0, 8.0]])

el = x[: , 1]
print(el)

print(el.mean())

slice=x[[1,2]]
print(slice)
print(slice[slice>2])

[2. 4. 7.]
4.333333333333333
[[1. 4. 2.]
 [6. 7. 8.]]
[4. 6. 7. 8.]


## Exercise 2 Array accessing to update
Given the previous array x = [[3.0, 2.0, 5.0], [1.0, 4.0, 2.0], [6.0, 7.0, 8.0]]
1) set the values of the first column to 0, if they are greater than 2
2) then try to do the same for the first and third columns together. Does it work? 

In [27]:
x= np.array([[3.0, 2.0, 5.0], [1.0, 4.0, 2.0], [6.0, 7.0, 8.0]])
print(x)

mask = x[:, 0 ]>2
x[:,0][mask]=0
print("first update\n", x)

x= np.array([[3.0, 2.0, 5.0], [1.0, 4.0, 2.0], [6.0, 7.0, 8.0]])
mask = x[:, [0,2]]>2
x[:,[0,2]][mask]=0
print("second update\n", x)

a= x[:, [0,2]]
a[mask]=0
print(a)


[[3. 2. 5.]
 [1. 4. 2.]
 [6. 7. 8.]]
first update
 [[0. 2. 5.]
 [1. 4. 2.]
 [0. 7. 8.]]
second update
 [[3. 2. 5.]
 [1. 4. 2.]
 [6. 7. 8.]]
[[0. 0.]
 [1. 2.]
 [0. 0.]]


## Exercise 3 Array concatenation and reshaping
Given two arrays x1 = [[3,1], [2,4]] and x2 = [[3, 4], [2,4], [2,5]]

Try to concatenate them vertically and then horizontally
If something does not work try to reshape the arrays so that you can concatenate (or stack) them.


In [ ]:
s